//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myGenieNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInfo
    {
        public long AdditionalInfo_Id { get; set; }
        public string AdditionalInfo_Background { get; set; }
        public string AdditionalInfo_CurrentJobTitle { get; set; }
        public string AdditionalInfo_CompanyName { get; set; }
        public string AdditionalInfo_EducationalInstitute { get; set; }
        public string AdditionalInfo_EducationLevel { get; set; }
        public string AdditionalInfo_Location { get; set; }
        public Nullable<long> AdditionalInfo_AlterPhoneNumber { get; set; }
        public string AdditionalInfo_AlterEmail { get; set; }
    }
}
