//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myGenieNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signupformembership
    {
        public long member_Id { get; set; }
        public string member_firstname { get; set; }
        public string member_lastname { get; set; }
        public string member_emailaddress { get; set; }
        public string member_preferredusername { get; set; }
        public string member_password { get; set; }
        public string member_confirmpassword { get; set; }
        public string emailaddress { get; set; }
        public string old_password { get; set; }
        public string new_password { get; set; }

    }
}
